In [34]:
import torch
torch.set_printoptions(sci_mode=False)

In [2]:
inputs = torch.randn(6, 3)  # 6 samples, each vector length 3
print(inputs)

tensor([[-0.2728,  0.8483, -0.6835],
        [-0.5035, -0.1803, -1.4679],
        [ 0.1080,  1.9712, -1.5753],
        [-0.5000,  0.6529, -0.7750],
        [-0.2441,  0.4189,  1.3836],
        [-0.3643, -1.2531, -0.5631]])


In [3]:
input_query = inputs[1]
print(input_query)

tensor([-0.5035, -0.1803, -1.4679])


In [5]:
input_1 = inputs[0]

In [6]:
input_query@input_1

tensor(0.9877)

In [17]:
attn_weights = []
for idx, tensor in enumerate(inputs):
    attn_weights.append((inputs[1]@tensor).item())

attn_weights

[tensor(0.9877),
 tensor(2.4409),
 tensor(1.9028),
 tensor(1.2717),
 tensor(-1.9837),
 tensor(1.2359)]

In [26]:
# Normalization using softmax
def softmax_naive(x):
    return torch.exp(x)/ (torch.exp(x).sum(dim=0))

attn_weights = softmax_naive(torch.tensor(attn_weights))
print(attn_weights)

tensor([0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228])


In [20]:
torch.softmax(torch.tensor(attn_weights), dim=0)

tensor([0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228])

In [30]:
context_vector = torch.zeros(inputs[1].shape)
for idx, x_i in enumerate(inputs):
    context_vector = context_vector + attn_weights[idx]*x_i

print(context_vector)


tensor([-0.3162,  0.4104, -1.2051])


 A simple self attention mechanism without trainable weights

In [ ]:
attn_scores = torch.empty(6,6)
for i, x_i in enumerate(inputs):
     for j, x_j in enumerate(inputs):
        attn_scores[i, j] = x_i@x_j
print(attn_scores)
# These are attn_scores, not yet normalized

tensor([[ 1.2611,  0.9877,  2.7194,  1.2199, -0.5237, -0.5787],
        [ 0.9877,  2.4409,  1.9028,  1.2717, -1.9837,  1.2359],
        [ 2.7194,  1.9028,  6.3790,  2.4538, -1.3802, -1.6224],
        [ 1.2199,  1.2717,  2.4538,  1.2768, -0.6768, -0.1996],
        [-0.5237, -1.9837, -1.3802, -0.6768,  2.1494, -1.2151],
        [-0.5787,  1.2359, -1.6224, -0.1996, -1.2151,  2.0200]])


In [36]:
attn_scores_ = inputs@inputs.T

In [ ]:
# Normalization
attn_weights = torch.softmax(attn_scores, dim=1)
attn_weights_ = torch.softmax(attn_scores_, dim=1)
print(attn_weights)
print(attn_weights_)

tensor([[0.1361, 0.1036, 0.5852, 0.1306, 0.0228, 0.0216],
        [0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228],
        [0.0243, 0.0108, 0.9455, 0.0187, 0.0004, 0.0003],
        [0.1441, 0.1518, 0.4950, 0.1526, 0.0216, 0.0349],
        [0.0571, 0.0133, 0.0243, 0.0490, 0.8277, 0.0286],
        [0.0436, 0.2677, 0.0154, 0.0637, 0.0231, 0.5865]])
tensor([[0.1361, 0.1036, 0.5852, 0.1306, 0.0228, 0.0216],
        [0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228],
        [0.0243, 0.0108, 0.9455, 0.0187, 0.0004, 0.0003],
        [0.1441, 0.1518, 0.4950, 0.1526, 0.0216, 0.0349],
        [0.0571, 0.0133, 0.0243, 0.0490, 0.8277, 0.0286],
        [0.0436, 0.2677, 0.0154, 0.0637, 0.0231, 0.5865]])
