In [1]:
import torch

In [2]:
inputs = torch.randn(6, 3)  # 6 samples, each vector length 3
print(inputs)

tensor([[-0.2728,  0.8483, -0.6835],
        [-0.5035, -0.1803, -1.4679],
        [ 0.1080,  1.9712, -1.5753],
        [-0.5000,  0.6529, -0.7750],
        [-0.2441,  0.4189,  1.3836],
        [-0.3643, -1.2531, -0.5631]])


In [3]:
input_query = inputs[1]
print(input_query)

tensor([-0.5035, -0.1803, -1.4679])


In [5]:
input_1 = inputs[0]

In [6]:
input_query@input_1

tensor(0.9877)

In [17]:
attn_weights = []
for idx, tensor in enumerate(inputs):
    attn_weights.append((inputs[1]@tensor).item())

attn_weights

[tensor(0.9877),
 tensor(2.4409),
 tensor(1.9028),
 tensor(1.2717),
 tensor(-1.9837),
 tensor(1.2359)]

In [19]:
# Normalization using softmax
def softmax_naive(x):
    return torch.exp(x)/ (torch.exp(x).sum(dim=0))

res = softmax_naive(torch.tensor(attn_weights))
print(res)

tensor([0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228])


In [20]:
torch.softmax(torch.tensor(attn_weights), dim=0)

tensor([0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228])

In [ ]:
# Context Vector
# Each attention weight corresponds to one input row.
# Multiply each row by its scalar weight and reduce each row to one value.
weighted_inputs = inputs * res.unsqueeze(1)  # shape: [6, 3]
context = weighted_inputs.sum(dim=1)  # shape: [6]
print("attention weights:", res)
print("weighted inputs:", weighted_inputs)
print("context values per row:", context)
print("context shape:", context.shape)

attention weights: tensor([0.0958, 0.4098, 0.2393, 0.1273, 0.0049, 0.1228])
context vector: tensor([-0.3162,  0.4104, -1.2051])
context shape: torch.Size([3])
